//
// Created by 陈 on 2022-11-15.
//

#ifndef GAZPREABASE_ASTPRINTERPASSWITHTYPES_H
#define GAZPREABASE_ASTPRINTERPASSWITHTYPES_H


class ASTPrinterPassWithTypes {

};


#endif //GAZPREABASE_ASTPRINTERPASSWITHTYPES_H
