//
// Created by 陈 on 2022-11-14.
//

#ifndef GAZPREABASE_TUPLEEXPLICITTYPECASTPASS_H
#define GAZPREABASE_TUPLEEXPLICITTYPECASTPASS_H


class TupleExplicitTypeCastPass {

};


#endif //GAZPREABASE_TUPLEEXPLICITTYPECASTPASS_H
