//
// Created by 陈 on 2022-11-14.
//

#ifndef GAZPREABASE_TUPLECOMPARISONTOLOGICALPASS_H
#define GAZPREABASE_TUPLECOMPARISONTOLOGICALPASS_H


class TupleComparisonToLogicalPass {

};


#endif //GAZPREABASE_TUPLECOMPARISONTOLOGICALPASS_H
