//
// Created by 陈 on 2022-11-14.
//

#ifndef GAZPREABASE_TUPLENOTEQUALTRANSFORMATIONPASS_H
#define GAZPREABASE_TUPLENOTEQUALTRANSFORMATIONPASS_H


class TupleNotEqualTransformationPass {

};


#endif //GAZPREABASE_TUPLENOTEQUALTRANSFORMATIONPASS_H
