//
// Created by 陈 on 2022-11-14.
//

#ifndef GAZPREABASE_TUPLECOMPARISONTOMEMBERACCESSPASS_H
#define GAZPREABASE_TUPLECOMPARISONTOMEMBERACCESSPASS_H


class TupleComparisonToMemberAccessPass {

};


#endif //GAZPREABASE_TUPLECOMPARISONTOMEMBERACCESSPASS_H
